name: Vercel Next Deployment
env:
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  ALGOLIA_APPLICATION_ID: ${{ secrets.ALGOLIA_APPLICATION_ID }}
  ALGOLIA_API_KEY: ${{ secrets.ALGOLIA_API_KEY }}

on:
  push:
    branches:
      - release/1.0

jobs:
  release:
    runs-on: ubuntu-latest
    environment: vercel-deployments
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "18.x"
      - name: test
        run: |
          export CONFIG=$(cat ./config.next.json | jq -r tostring)
          echo $CONFIG
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - run: rm -rf .vercel
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --git-branch=release/1.0 --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build
      - name: Deploy Project Artifacts to Vercel
        run: |
          url="$(vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }})"
          vercel alias --token=${{ secrets.VERCEL_TOKEN }} --scope=${{ secrets.VERCEL_ORG_ID }} set "$url" docs-next.renative.org
      - name: Update Algolia index
        uses: addnab/docker-run-action@v3
        with:
          image: algolia/docsearch-scraper
          options: --env-file=algolia.env -e "CONFIG=$(cat ./config.next.json | tr -d '\n')"
            

